# PSM系统配置
psm:
  sys_iterations: 15 
  exp_iterations: 10
  query_iterations: 5
  scan_iterations: 1
  debug: False
  draw_graph: False


# AI配置
ai:
  # api config
  openai_base: "https://api.openai.com/v1"
  openai_key: "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"
  nvidia_key: "Enter your nvidia api key here"
  # hyperparameters
  temperature: 0


# 测试配置
test:
  test_path: "../bench/data.jsonl"
  output_path: "result"
  save_history: True # 是否保存历史记录
  save_command: True # 是否保存命令
  # models: ['gpt35turbo', 'gpt4omini', 'gpt4o']
  models: ['gpt35turbo']
  
